#!/bin/bash

CONFIG="$HOME/.config/waybar/config"
#STYLE="$HOME/.config/hypr/waybar/style.css"

# Create new css files and make your own styles

STYLE="$HOME/.config/waybar/style-everforest.css"

# Terminate already running bar instances
killall -q waybar

# Wait until the processes have been shut down
while pgrep -x waybar >/dev/null; do sleep 1; done

if [[ ! $(pidof waybar) ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi

