------------------------------
---       HYPRLAND         ---
------------------------------

------------------------------
---       MONITORS         ---
------------------------------

-- Documentation: https://wiki.hypr.land/Configuring/Basics/Monitors
--                https://wiki.hypr.land/Configuring/Advanced-and-Cool/Expanding-functionality

-- Generated by nwg-displays on 2026-06-09 at 15:28:59. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "3840x2160@60.0",
    position = "0x0",
    scale = 1.5
})
hl.monitor({
    output = "DP-2",
    mode = "3840x2160@60.0",
    position = "2560x0",
    scale = 1.5
})
